### ISSUE TITLE
Add use method that accepts another router instance.

### ISSUE THREAD

**Issue by johndavedecano** [evantbyrne/router#1]
Please add use method that accepts another Router instance. This will us easily organize things by modules.

$base = '/users';
$userRoutes = new Route($base);

$parent = new Route('/');

$parent->use($userRoutes);

**Comment by evantbyrne** [comment]
Hey John,

First of all, sorry for the late response! This is a purely experimental project, and as such I will not be accepting feature requests. However, please feel free to fork the repository and make changes as you see fit!
